### ISSUE TITLE
Agenda proposal for the F2F meeting on Sep 10th 2025 in Stuttgart

### ISSUE THREAD

**Issue by mkurzman** [OpenChain-Project/Automotive-WG#1]
## Suggested agenda

1.  Software Defined Vehicle / Eclipse SDV [1] – how will a future software
supply chain will look like and what needs to be expected with OTA-updates in
the vehicles?
2. Catena-X [2] / Eclipse Tractus-X [3] – are there potential synergies
with the OpenChain community and is there also a supply chain for data?
3. COVESA [4] – what needs to be considered in the automotive software
supply chain when vehicles will become more and more connected?
4. Linux ELISA [5] / SPDX Safety Profile [6] – how can the safety
requirements be covered along the automotive software supply chain?
5. End-to-end (Open Source) Software Management along the supply
chain, tool updates and the need of standardized interfaces
6. News/Update about regulations (EU, US, …)  impacting the
automotive supply chain and how OpenChain standards can help?

Who can help in getting the respective speakers for the topics?
Further suggestions?

[1] https://sdv.eclipse.org/

[2] https://catena-x.net/
[3] https://eclipse-tractusx.github.io/
[4] https://covesa.global/

[5] https://elisa.tech/

[6] e.g.
<https://fosdem.org/2024/events/attachments/fosdem-2024-3211-applicatio
n-of-the-spdx-safety-profile-in-the-safety-scope-of-the-zephyr-project/slide
s/22714/SPDX_Safety_Profile_-_Zephyr_StrictDoc_Example_4BSSrzW.pdf>

**Comment by shanecoughlan** [comment]
Turned into page so people can push PR against it:
https://github.com/OpenChain-Project/Automotive-WG/blob/main/2024-09-10-workshop-agenda.md

**Comment by shanecoughlan** [comment]
Closing this issue as work has moved to the main agenda md in the repo.
